# Exposes endpoints to view through actuator.
management:
  endpoints:
    jmx:
      exposure:
        include: "*"

# Database configuration and connection.
spring:
  datasource:
    username: "sa"
    password: "UlF8QCHp2yCh7q6JGN4VDeY7"
    url: "jdbc:sqlserver://localhost;databaseName=ecommerce;encrypt=true;trustServerCertificate=true"
  jpa:
    hibernate:
      ddl-auto: update
# SMTP configuration.
  mail:
    host: "localhost"
    port: 25

# Encryption configuration.
encryption:
  salt:
    rounds: 10

# JWT configuration.
jwt:
  algorithm:
    key: "my-secret-token-to-change-in-production-environment"
  issuer: "ecommerce"
  expiryInSeconds: 1200

# Email Configuration
email:
  address:
    from: "no-reply@ecomm.co.za"

# General Application Configuration.
app:
  frontend:
    url: "http://ecomm.com"
